### PR TITLE
self-training

### PR DESCRIPTION
**Pull request by dorancemc**

### CODE REVIEW

**Comment by wmunoz** [comment]
Thanks for the first PR!!

**Comment by 4ndr4s** [comment]
we need to find the best way to sort the documentation, maybe take a look of this as example:
https://github.com/nathanpeck/awesome-ecs/blob/master/README.md

**Comment by wmunoz** [comment]
that's a good example

**Comment by 4ndr4s** [comment]
https://github.com/mikewootini/awesome-devops check another one

**Review by wmunoz — APPROVED** [review]
lets add this one as a baseline to start. Lets improve commit name next time

**Pull request merged**
